### ISSUE TITLE
Create an extension for the Data Science VM to install the OKPy client

### ISSUE THREAD

**Issue by marrobi** [icokpy/ok#6]

**Comment by TempestVanSchaik** [comment]
- [ ] Get rid of period in OK.py name
- [ ] check status file on Linux VM for the deployment error
- [ ] Edit template to create Windows VM

- [ ] check OK.py client works and connect to OK server

**Comment by TempestVanSchaik** [comment]
# How to install OKpy on Windows (in an Anaconda environment):

conda create --name OKenv
activate OKenv
conda install pip
pip install -r https://raw.githubusercontent.com/Cal-CS-61A-Staff/ok-client/master/requirements.txt
conda install ipykernel 
python -m ipykernel install --user --name myenv --display-name "OKenv"

conda install jupyter
jupyter notebook #make sure to select Kernel>change kernel and select OKenv

**Comment by taupalosaurus** [comment]
Same on a linux DSVM inside a venv:

```
#!/bin/sh

export ENV_NAME=okpyenv2

python3 -m venv $ENV_NAME --without-pip
source $ENV_NAME/bin/activate
curl https://bootstrap.pypa.io/get-pip.py | python
deactivate

source $ENV_NAME/bin/activate
wget https://raw.githubusercontent.com/Cal-CS-61A-Staff/ok-client/master/requirements.txt
pip install -r requirements.txt
pip install -U okpy

#test
python -c "from client.api.notebook import Notebook"
deactivate
```

**Comment by taupalosaurus** [comment]
At this stage, linux deployment script is broken. Several options were considered, none works so far

  - install directly with pip fails because of permissions

  - creating a venv fails because I can't manage to get it installed in the right location with the right permissions

 - within a conda env fails: root is python2 and python3 is required apparently; py35 didn't work for some reason, creating an ad hoc env failed for some other reason

**Comment by taupalosaurus** [comment]
### How to setup the jupyter server on linux

```
# activate venv
source ~/okpyenv2/bin/activate

# create custome python kernel corresponding to the venv
pip install ipykernel
python -m ipykernel install --user --name okpyenv2 --display-name "Python okpy"

# create minimal files to use jupyter as server and override some machine-wide settings
# TODO these should be improved
jupyter-notebook --generate-config
jupyter-notebook password

jupyter-notebook --no-browser --notebook-dir '/home/barral/ese' --port 9999 --ip 0.0.0.0
# then go to https://ip.of.the.vm:9999 and bypass dodgy certificate warning
```

**Comment by marrobi** [comment]
@TempestVanSchaik what was the last status of this, are we in a position to do a PR back to the DS VM repo? Thanks.

**Comment by TempestVanSchaik** [comment]
Hi @marrobi I'll wrap this up today and tomorrow
